name: Change Composer.json on Push to Master

on:
  push:
    branches:
      - master

jobs:
  change-composer-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update Composer.json
        run: |
          # Get the current version from composer.json
          current_version=$(jq -r .version composer.json)
          new_version=$(date +"%s") 

          echo "Current Unix timestamp: $new_version"
          
          # Modify the composer.json file as needed
          sed -i "s/\"version\": \"$current_version\"/\"version\": \"$new_version\"/g" composer.json

          # Commit the changes
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add composer.json
          git commit -m "Update composer.json file"

          # Push the changes back to the repository
          # git remote set-url origin https://drapic88:$GH_TOKEN@github.com/drapic88/mono-repo-main.git
          git push
        env:
          GH_TOKEN: ${{ secrets.ACC_TOKEN }}

