name: Pull Subtree and Push

on:
  push:
    branches: [main]

jobs:
  pull-subtree-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Clone remote repository
        run: git clone https://github.com/drapic88/mono-repo-main.git main-repo

      - name: Set up Git
        run: |
          cd main-repo
          git config --global user.email "dragan.rapic@revendo.ch"
          git config --global user.name "Dragan Rapić"

      - name: Fetch subtree
        run: git fetch https://github.com/drapic88/mono-repo-sub-repo-1.git main:subrepo-1-main

      - name: Merge subtree
        run: git checkout main && git merge -s ours --no-commit subrepo-1-main

      - name: Push subtree to GitHub
        run: git push origin main
