name: Pull Subtree and Push

on:
  push:
    branches: [ staging ]

jobs:
  pull-subtree-and-push:
    runs-on: ubuntu-latest

    steps:         
      - name: Clone remote repository
        run: git clone https://github.com/drapic88/mono-repo-main.git main-repo
  
      - name: Pull subtree
        run: |
          cd main-repo
          git checkout staging
          git config --global user.email "dragan.rapic@revendo.ch" 
          git config --global user.name "Dragan Rapić" 
          git subtree pull --prefix subrepo-2 https://github.com/drapic88/mono-repo-sub-repo-2.git staging

      - name: Push subtree to GitHub
        run: |
          cd main-repo
          git checkout staging
          git remote set-url origin https://drapic88:$GH_TOKEN@github.com/drapic88/mono-repo-main.git
          git push
        env:
          GH_TOKEN: ${{ secrets.NOVI_TOKEN }}
